CREATE TABLE IF NOT EXISTS Users (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email varchar(100) NOT NULL,
            login varchar(50) NOT NULL,
            name varchar(100),
            birthday date
          );

CREATE TABLE IF NOT EXISTS Friend_relationship (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            accepting_friend_id  bigint REFERENCES Users(id),
            subscribing_friend_id bigint REFERENCES Users(id)
          );

CREATE TABLE IF NOT EXISTS Motion_Picture_Associations (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name varchar(20)
--            description varchar(200)
          );

CREATE TABLE IF NOT EXISTS Genres (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name varchar(100)
--            english_name varchar(50),
--            russian_name varchar(100)
          );

CREATE TABLE IF NOT EXISTS Films (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name varchar(100) NOT NULL,
            description varchar(200),
            release_date date,
            duration bigint,
            mpa_id bigint REFERENCES Motion_Picture_Associations(id),
            CONSTRAINT description_max_length CHECK (char_length(description) <= 200),
            CONSTRAINT duration CHECK (duration > 0)
          );

CREATE TABLE IF NOT EXISTS Films_genres (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            film_id bigint REFERENCES Films(id),
            genre_id bigint REFERENCES Genres(id)
          );

CREATE TABLE IF NOT EXISTS User_likes (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            film_id bigint REFERENCES Films(id),
            user_id bigint REFERENCES Users(id)
          );